#cloud-config

ssh_authorized_keys:
  - ssh-rsa ADMINKEY admin

repo_update: true
repo_upgrade: all

packages:
  - python3
  - python3-pip
  - python3-venv
  - sagemath
  - afl++
  - gdb

write_files:
  - path: /etc/ssh/sshd_config.d/90_noroot
    content: |
      PermitRootLogin no
      PubkeyAuthentication yes
      PasswordAuthentication no

  - path: /tmp/initial-user-setup.sh
    content: |
      #!/bin/bash

      export CTF_VENV="/home/ubuntu/.venvs/ctf"

      mkdir -p $CTF_VENV
      python3 -m venv $CTF_VENV

      source $CTF_VENV/bin/activate

      python3 -m pip install angr pwntools

runcmd:
  - systemctl reload sshd
  - sudo -u ubuntu pip install tldr
  - sudo -u ubuntu bash /tmp/initial-user-setup.sh
  - touch /home/ubuntu/init-setup-done
